name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run type checking
        run: pnpm check

      - name: Run linting
        run: pnpm lint

      - name: Run tests
        run: pnpm test -- --run

      - name: Build project
        run: pnpm build

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build for production
        run: pnpm build
        env:
          PUBLIC_RELAY_URL: ${{ secrets.PUBLIC_RELAY_URL }}

      - name: Upload to Bunny.net
        if: success()
        env:
          BUNNY_STORAGE_KEY: ${{ secrets.BUNNY_STORAGE_KEY }}
          BUNNY_STORAGE_ZONE: ${{ secrets.BUNNY_STORAGE_ZONE }}
          BUNNY_CDN_URL: ${{ secrets.BUNNY_CDN_URL }}
        run: |
          # Install Bunny CLI or use curl to upload
          # This is a placeholder - replace with actual Bunny.net deployment commands
          echo "Deploy to Bunny.net storage zone"
          # Example using curl:
          # find build -type f -name "*" | while read file; do
          #   rel_path=${file#build/}
          #   curl -X PUT \
          #     -H "AccessKey: $BUNNY_STORAGE_KEY" \
          #     -T "$file" \
          #     "https://storage.bunnycdn.com/$BUNNY_STORAGE_ZONE/$rel_path"
          # done