name: Deploy Relay

on:
  push:
    branches:
      - master
    paths:
      - 'relay/**'
      - '.github/workflows/deploy-relay.yml'
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache-dependency-path: relay/go.sum

      - name: Build relay binary
        run: |
          cd relay
          go build -o notemine-relay -ldflags="-s -w" ./cmd/relay

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.VPS_SSH_PORT || 22 }} -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Run Ansible playbook
        run: |
          cd ansible
          ansible-playbook -i inventory.yml playbook-relay.yml \
            --extra-vars "relay_binary_path=../relay/notemine-relay" \
            --extra-vars "ansible_user=${{ secrets.VPS_USER }}" \
            --extra-vars "ansible_host=${{ secrets.VPS_HOST }}" \
            --extra-vars "ansible_port=${{ secrets.VPS_SSH_PORT || 22 }}"
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
